### PR TITLE
API requests written and API responses available for rendering in DOM

### PR DESCRIPTION
**Pull request by codewizard-dt**
Cost of Living API response object
Screen Shot 2022-07-07 at 8 09 04 PM
GeoDB Cities API response object
Screen Shot 2022-07-07 at 8 09 14 PM
Sample Price of Goods
Screen Shot 2022-07-07 at 8 09 25 PM
Sample Category of Goods
Screen Shot 2022-07-07 at 8 09 35 PM

DEMO -- Will be removed when HTML elements are finished, currently just to show the API responses
Screen Shot 2022-07-07 at 8 14 20 PM

### CODE REVIEW

**Review by mmdoza002 — COMMENTED** [review]
Looks good!

**Review by mmdoza002 — COMMENTED** [review]
Looks good!

**Review by littletonjeffrey — APPROVED** [review]
Nice work

**Review by mmdoza002 — APPROVED** [review]
Great Job !

**Pull request merged**
