### PR TITLE
added slide on carousel, started style mods

### PR DESCRIPTION
**Pull request by littletonjeffrey**
-added slide to each carousel
-changed sports to misc (info seemed more pertinent)
-changed background color
-started spacing out elements
-added placeholders and style to header

### CODE REVIEW

**Review by codewizard-dt — CHANGES_REQUESTED** [review]
Regarding the changes in style.css .... you're reverting changes that we made as a group that impact the `index.html`.  I think if you do a `git merge main` it will update them and then you can push again

**Comment by littletonjeffrey** [comment]
Sorry about the confusion, I thought we were going for a little bit of a cleaner, more modern look.  I'm not totally finished yet so it can wait til morning and everyone can have a look then.  If people like it, cool.  If they like the colors the other way then we can just disregard the pull request.

**Comment by codewizard-dt** [comment]
I'm not talking about your new changes.... just some of the stuff we did today.  Namely this:

Screen Shot 2022-07-11 at 9 05 34 PM

**Comment by littletonjeffrey** [comment]
Huh, I didn't change anything myself in that area.  It's possible my main is out of sync.  I tried git merging into the branch I'm pushing but it said I was up to date.  Lemme see if I can square up why the two aren't lining up.

**Comment by codewizard-dt** [comment]
We can square it up tomorrow too. No worries

**Comment by littletonjeffrey** [comment]
Hopefully better now, sorry for all the headache.  Good lesson in not getting distracted from git pulling

**Review by Castoreno05 — APPROVED** [review]
Looking good thanks Jeffrey!

**Review by codewizard-dt — APPROVED** [review]
all good

**Pull request merged**
