### PR TITLE
Changed the button to a toggle. Also made it more responsive.

### PR DESCRIPTION
**Pull request by Castoreno05**
Hope this looks better guys. If its not just let me know and I can change it 👍

### CODE REVIEW

**Review by codewizard-dt — CHANGES_REQUESTED** [review]
I think the styling is much better.  There's a few things need fixing tho.  See how the `search input` overlaps the `search label`?
Screen Shot 2022-07-07 at 5 59 07 PM
Good job with the tabs!!  They're responsive too
- [x] fix overlap issue in search bar
- [x] update the text in the tabs to reflect our wireframe
- [x] create HTMLElements that correspond to the tabs you've created
- [x] on smaller screens I think the column should be full width, according to your classes, but it doesn't quite work.  Double check the class names maybe? They look like bootstrap classes, does Materialize use similarly named classes?


Screen Shot 2022-07-07 at 6 02 41 PM

**Review by codewizard-dt — CHANGES_REQUESTED** [review]
I realized why the column sizing isn't working as expected.... this .card-panel css rule is forcing the column to a specific size.  Try using min-width instead

Screen Shot 2022-07-07 at 6 08 31 PM

**Review by codewizard-dt — APPROVED** [review]
Love the tabs

**Review by littletonjeffrey — APPROVED** [review]
Great job

**Pull request merged**
